# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funmash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='myimg71830', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
